#!/bin/sh
set -eu
# Prevent inherited credentials or repository/password overrides from winning.
unset RESTIC_REPOSITORY RESTIC_REPOSITORY_FILE RESTIC_PASSWORD RESTIC_PASSWORD_FILE
unset RESTIC_PASSWORD_COMMAND AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN AWS_PROFILE AWS_DEFAULT_PROFILE AWS_REGION AWS_DEFAULT_REGION
set -a
. /etc/developer-platform/backup/restic.env
set +a
exec /usr/bin/restic "$@"
